-- insert ITEMS_TYPES
insert into ITEMS_TYPES (NAME_ITYPES, DATE_ITYPES) values
('Standard',getdate()),
('Mini calla',getdate()),
('Mini carnation',getdate()),
('Football mums',getdate()),
('Cremons',getdate()),
('Anastasia - spider',getdate()),
('Seafood',getdate()),
('Mini green',getdate()),
('Oriental',getdate()),
('Asiatic',getdate()),
('Cdn',getdate()),
('Daisy',getdate()),
('Garden',getdate())

-- insert PRESENTATIONES
insert into PRESENTATIONES(NAME_PTYPE, DATE_PTYPE) values
('Bulk',getdate()),
('Bqt',getdate()),
('Arrangement',getdate()),
('Garland',getdate()),
('Table top tree',getdate()),
('Wreath',getdate()),
('Wedding',getdate()),
('Box',getdate()),
('Plants',getdate()),
('Bags',getdate()),
('Cb',getdate())

-- insert process
INSERT INTO PROCESS (TYPE_PROCESS, DATE_PROCESS) VALUES 
('Natural',getdate()),
('Painted',getdate()),
('Balsam',getdate()),
('Painted glitter',getdate()),
('Glitter',getdate()),
('Tinted',getdate())

-- insert into species
INSERT INTO SPECIES(NAME_SPECIE, DATE_SPECIE) VALUES
('Anthuriums',GETDATE()),
('Calla',GETDATE()),
('Carnation',GETDATE()),
('Christmas',GETDATE()),
('Cocculus',GETDATE()),
('Combo greens',GETDATE()),
('Combo hydrangea & petals',GETDATE()),
('Combo minicalla & lilies',GETDATE()),
('Combo oriental & asiatic lilies',GETDATE()),
('Combo rose & spray rose',GETDATE()),
('Combo roses & rose petals',GETDATE()),
('Combo wedding',GETDATE()),
('Dahlias',GETDATE()),
('Disbuds',GETDATE()),
('Eucalyptus',GETDATE()),
('Flax',GETDATE()),
('Food',GETDATE()),
('Gypsophilia',GETDATE()),
('Hanging plants',GETDATE()),
('Hydrangea',GETDATE()),
('Hydrangea petals',GETDATE()),
('Hypericum',GETDATE()),
('Israeli ruscus',GETDATE()),
('Kangaroo',GETDATE()),
('Lilies',GETDATE()),
('Lily grass',GETDATE()),
('Mixbqt',GETDATE()),
('Peonies',GETDATE()),
('Pittosporum',GETDATE()),
('Pompon',GETDATE()),
('Pot plants',GETDATE()),
('Rose petals',GETDATE()),
('Roses',GETDATE()),
('Viburnum',GETDATE())

-- varietys
insert into VARIETIES(NAME_VARIETY, DATE_VARIETY ) values
('Assorted',getdate()),
('Red',getdate()),
('Picasso',getdate()),
('Black',getdate()),
('White',getdate()),
('Lavender - white',getdate()),
('Pink - white',getdate()),
('Purple - pink',getdate()),
('Yellow - purple',getdate()),
('Black - pink',getdate()),
('Black - white',getdate()),
('Black - yellow',getdate()),
('Red - white',getdate()),
('White - blue',getdate()),
('White - green',getdate()),
('White - light blue',getdate()),
('White - orange',getdate()),
('White - hot pink',getdate()),
('White - pink',getdate()),
('White - purple',getdate()),
('White - red',getdate()),
('White - yellow',getdate()),
('Hot pink',getdate()),
('Peach',getdate()),
('Purple',getdate()),
('Lavender',getdate()),
('Orange',getdate()),
('Pink',getdate()),
('Yellow',getdate()),
('Burgundy ',getdate()),
('Novelties',getdate()),
('Green',getdate()),
('Green ',getdate()),
('Holly',getdate()),
('Pine cones',getdate()),
('Antique green',getdate()),
('Blue',getdate()),
('Hulk',getdate()),
('Kiwi',getdate()),
('Lime green',getdate()),
('White - assorted',getdate()),
('White - bicolor',getdate()),
('White - peach',getdate()),
('Hot pink - white',getdate()),
('Light pink',getdate()),
('Pink-green-white',getdate()),
('Yellow-orange-green',getdate()),
('Bronze',getdate()),
('Lime',getdate()),
('Neon green',getdate()),
('Neon hot pink',getdate()),
('Neon orange',getdate()),
('Neon yellow',getdate()),
('Metallic aqua',getdate()),
('Metallic black',getdate()),
('Metallic blue',getdate()),
('Metallic dark blue',getdate()),
('Gold',getdate()),
('Metallic green',getdate()),
('Metallic hot pink',getdate()),
('Metallic lavender',getdate()),
('Metallic lemon green',getdate()),
('Metallic light pink',getdate()),
('Metallic orange',getdate()),
('Metallic peach',getdate()),
('Metallic pink',getdate()),
('Metallic purple',getdate()),
('Metallic red',getdate()),
('Silver',getdate()),
('Metallic yellow',getdate()),
('Tritone green - yellow - orange',getdate()),
('Triton lavander - hot pink - turquoise',getdate()),
('Tritone purple - sky blue - yellow',getdate()),
('Tritone yellow - orange - black',getdate()),
('Aquamarine',getdate()),
('Brown',getdate()),
('Burgundy',getdate()),
('Dark blue',getdate()),
('Grape',getdate()),
('Kelly green',getdate()),
('Magenta',getdate()),
('Mustard',getdate()),
('Blue patriotic',getdate()),
('Peach - brown',getdate()),
('Pink - blue',getdate()),
('Yellow - blue',getdate()),
('Yellow - brown',getdate()),
('White - black',getdate()),
('White - brown',getdate()),
('Teal blue',getdate()),
('White - lila',getdate()),
('Rainbow chameleon',getdate()),
('Variegated',getdate()),
('Crabs',getdate()),
('Gypso perfecta / millon star',getdate()),
('Assorted plants',getdate()),
('Ivy green',getdate()),
('Marble queen',getdate()),
('Philo brasil',getdate()),
('Pothos golden',getdate()),
('Pothos jade',getdate()),
('Pothos scindapsus',getdate()),
('Spider hanging basket',getdate()),
('Rainbow',getdate()),
('Pastel',getdate()),
('Antique pink',getdate()),
('Assorted antique',getdate()),
('Antique red',getdate()),
('Aqua',getdate()),
('Lemon green',getdate()),
('Shocking blue',getdate()),
('Assorted - fall',getdate()),
('Lilac',getdate()),
('Blueberry',getdate()),
('Dark purple',getdate()),
('Light aqua',getdate()),
('Light blue',getdate()),
('Party',getdate()),
('Patriotic asst.',getdate()),
('Blue - white',getdate()),
('Pastel asst.',getdate()),
('Pastel blue',getdate()),
('Pastel hot pink',getdate()),
('Pastel green',getdate()),
('Pastel orange',getdate()),
('Pastel purple',getdate()),
('Pastel violet',getdate()),
('Sandra bernhardt',getdate()),
('Pineapple',getdate()),
('Spath',getdate()),
('Bamboo',getdate()),
('Bonsai',getdate()),
('Bromelias',getdate()),
('Orchid',getdate()),
('Mini orchids',getdate()),
('Red - pink',getdate()),
('Red - white - pink',getdate()),
('Red - yellow',getdate()),
('Red - color',getdate()),
('Aphrodite',getdate()),
('Baronesse',getdate()),
('White cloud',getdate()),
('Yves piaget',getdate()),
('Free spirit',getdate()),
('Vitality',getdate()),
('Pink piano',getdate()),
('Alabaster',getdate()),
('Mariatheresia',getdate()),
('Mythos',getdate()),
('Mayra',getdate()),
('Romantic',getdate()),
('Pink o hara',getdate()),
('Sunset',getdate()),
('Cara luna',getdate()),
('Monster',getdate()),
('Catalina',getdate()),
('White - gold',getdate()),
('White - irisdecense',getdate()),
('Bicolor white - pink',getdate()),
('Bicolor yellow - red',getdate()),
('Green - white',getdate()),
('Orange - white',getdate()),
('Purple - white',getdate()),
('Red - gold',getdate()),
('Red - silver',getdate()),
('Turquoise',getdate()),
('White - silver',getdate()),
('Yellow - white',getdate()),
('Crème de la crème',getdate()),
('Pink floyd',getdate()),
('Tenerife',getdate()),
('Ocean song',getdate()),
('Deep purple',getdate()),
('Senorita',getdate()),
('Blushing akito',getdate()),
('Titanic',getdate()),
('Nina',getdate()),
('Iguana',getdate()),
('Cabaret',getdate()),
('Explorer',getdate()),
('White chocolate',getdate()),
('First lady',getdate()),
('Bikini',getdate()),
('Sonrisa',getdate()),
('Cubana',getdate()),
('Hummer',getdate()),
('Bicolor',getdate()),
('Topaz',getdate()),
('Imagination',getdate()),
('Freedom',getdate()),
('Forever young',getdate()),
('Movie star',getdate()),
('Vendela',getdate()),
('Mondial',getdate()),
('High and yellow',getdate()),
('High and magic',getdate()),
('Circus',getdate()),
('Farfalla',getdate()),
('Cherry brandy',getdate()),
('Twlight',getdate()),
('Riviera',getdate()),
('Hot merengue',getdate()),
('Wild spirit',getdate()),
('Black magic',getdate()),
('Bright color assorted',getdate()),
('Green tea',getdate()),
('Hot lady',getdate()),
('High and mora',getdate()),
('Cool water',getdate()),
('Moody blue',getdate()),
('Opus',getdate()),
('Sweet akito',getdate()),
('Samba pa ti',getdate()),
('Tropical amazone',getdate()),
('Wow',getdate()),
('Manitou',getdate()),
('Vodoo',getdate()),
('High and orange',getdate()),
('Nectarine',getdate()),
('Sexy red',getdate()),
('White dove',getdate()),
('Polar star',getdate()),
('Dejavu',getdate()),
('Tara',getdate()),
('Swetness',getdate()),
('Wimbledon',getdate()),
('Purple haze',getdate()),
('Light pink - white',getdate())

-- color
insert into COLORS(NAME_COLOR, DATE_COLOR ) values
('Assorted',getdate()),
('Red',getdate()),
('Bicolor',getdate()),
('Black',getdate()),
('White',getdate()),
('Lavender - white',getdate()),
('Pink - white',getdate()),
('Purple - pink',getdate()),
('Yellow - purple',getdate()),
('Black - pink',getdate()),
('Black - white',getdate()),
('Black - yellow',getdate()),
('Red - white',getdate()),
('White - blue',getdate()),
('White - green',getdate()),
('White - light blue',getdate()),
('White - orange',getdate()),
('White - hot pink',getdate()),
('White - pink',getdate()),
('White - purple',getdate()),
('White - red',getdate()),
('White - yellow',getdate()),
('Hot pink',getdate()),
('Peach',getdate()),
('Purple',getdate()),
('Lavender',getdate()),
('Orange',getdate()),
('Picasso',getdate()),
('Pink',getdate()),
('Yellow',getdate()),
('Burgundy ',getdate()),
('White - lavender',getdate()),
('White - light pink',getdate()),
('Green',getdate()),
('Green ',getdate()),
('Brown',getdate()),
('Blue',getdate()),
('Lime green',getdate()),
('White - assorted',getdate()),
('White - bicolor',getdate()),
('White - peach',getdate()),
('Hot pink - white',getdate()),
('Light pink',getdate()),
('Pink-green-white',getdate()),
('Yellow-orange-green',getdate()),
('Bronze',getdate()),
('Lime',getdate()),
('Neon green',getdate()),
('Neon hot pink',getdate()),
('Neon orange',getdate()),
('Neon yellow',getdate()),
('Metallic aqua',getdate()),
('Metallic black',getdate()),
('Metallic blue',getdate()),
('Metallic dark blue',getdate()),
('Gold',getdate()),
('Metallic green',getdate()),
('Metallic hot pink',getdate()),
('Metallic lavender',getdate()),
('Metallic lemon green',getdate()),
('Metallic light pink',getdate()),
('Metallic orange',getdate()),
('Metallic peach',getdate()),
('Metallic pink',getdate()),
('Metallic purple',getdate()),
('Metallic red',getdate()),
('Silver',getdate()),
('Metallic yellow',getdate()),
('Tritone green - yellow - orange',getdate()),
('Triton lavander - hot pink - turquoise',getdate()),
('Tritone purple - sky blue - yellow',getdate()),
('Tritone yellow - orange - black',getdate()),
('Aquamarine',getdate()),
('Burgundy',getdate()),
('Dark blue',getdate()),
('Grape',getdate()),
('Kelly green',getdate()),
('Magenta',getdate()),
('Mustard',getdate()),
('Blue patriotic',getdate()),
('Peach - brown',getdate()),
('Pink - blue',getdate()),
('Yellow - blue',getdate()),
('Yellow - brown',getdate()),
('White - black',getdate()),
('White - brown',getdate()),
('Teal blue',getdate()),
('White - lila',getdate()),
('Rainbow chameleon',getdate()),
('N/a',getdate()),
('Rainbow',getdate()),
('Pastel',getdate()),
('Assorted antique',getdate()),
('Aqua',getdate()),
('Lemon green',getdate()),
('Shocking blue',getdate()),
('Assorted - fall',getdate()),
('Lilac',getdate()),
('Blueberry',getdate()),
('Dark purple',getdate()),
('Light aqua',getdate()),
('Light blue',getdate()),
('Novelties',getdate()),
('Party',getdate()),
('Patriotic asst.',getdate()),
('Blue - white',getdate()),
('Pastel asst.',getdate()),
('Pastel blue',getdate()),
('Pastel hot pink',getdate()),
('Pastel green',getdate()),
('Pastel orange',getdate()),
('Pastel purple',getdate()),
('Pastel violet',getdate()),
('Green - white',getdate()),
('Salmon',getdate()),
('Red - pink',getdate()),
('Red - white - pink',getdate()),
('Red - yellow',getdate()),
('Red - color',getdate()),
('Orange - peach',getdate()),
('White - gold',getdate()),
('White - irisdecense',getdate()),
('Bicolor white - pink',getdate()),
('Bicolor yellow - red',getdate()),
('Orange - white',getdate()),
('Purple - white',getdate()),
('Red - gold',getdate()),
('Red - silver',getdate()),
('Turquoise',getdate()),
('White - silver',getdate()),
('Yellow - white',getdate()),
('Cream',getdate()),
('Peachy pink',getdate()),
('Bicolor white - red',getdate()),
('Bright color assorted',getdate()),
('Light pink - white',getdate())

-- grade

insert into GRADES(NAME_GRADE, DATE_GRADE) values
('Large',getdate()),
('Medium',getdate()),
('Small',getdate()),
('40 - 50 cm',getdate()),
('Select',getdate()),
('N/a',getdate()),
('18 ft.',getdate()),
('9 ft.',getdate()),
('18 in',getdate()),
('48 in',getdate()),
('28 in',getdate()),
('36 in',getdate()),
('30 in',getdate()),
('24 in',getdate()),
('50 cm',getdate()),
('60 cm',getdate()),
('Jumbo',getdate()),
('40 cm',getdate()),
('70 cm',getdate()),
('50 - 60 cm',getdate()),
('Super colassal',getdate()),
('Colossal',getdate()),
('250 gr',getdate()),
('8 in',getdate()),
('Mini',getdate()),
('Super select',getdate()),
('55 - 60 cm',getdate()),
('40 - 60 cm',getdate()),
('6 in',getdate()),
('4 in',getdate()),
('5 in',getdate()),
('7 in',getdate()),
('1000 rose petals aprox. per bag',getdate()),
('90 cm',getdate())

-- cuts
insert into CUTS(NAME_CUT, DATE_CUT ) values
('N/a',getdate()),
('Regular cut',getdate()),
('4 blooms minimum per stem',getdate()),
('Open cut',getdate()),
('1',getdate()),
('0.8',getdate()),
('3-5 blooms',getdate()),
('Americano 2.5',getdate()),
('Americano 2',getdate()),
('0.2',getdate()),
('Punto 3',getdate())


-- materials

-- Type boxes
insert into(TYPEBOXE_BTYPE,DATECREATE_BTYPE) values('SB',getdate() ),
('PG',getdate() ),
('QB',getdate() ),
('Vendor',getdate() ),
('EB',getdate() ),
('HB',getdate() )
